### ISSUE TITLE
[FEATURE] Updating footer

### ISSUE THREAD

**Issue by Shaba1406** [arpitghura/typing-test#51] opened 2022-10-31 09:01 UTC
I want to add Footer for the website please assign this to me under hacktoberfest 2022.
@arpitghura

**Comment by arpitghura** [comment] 2022-10-31 09:03
Hey, @Shaba1406 Please check the website the footer is available already. 
If you want to make changes to the existing one, then please clarify.

**Comment by Shaba1406** [comment] 2022-10-31 09:12
Yes I want to give a look like this and to update the footer section.

![Typing Test _ Test and practice your typing skills - Google Chrome 31-10-2022 14_40_17](https://user-images.githubusercontent.com/97939567/198972722-694c6f53-f6d6-4317-8d1c-17a2f45cb43c.png)

**Comment by arpitghura** [comment] 2022-10-31 09:17
Okay @Shaba1406 It looks pretty good but needs some improvements like the copyright line should be placed at the bottom most part in center and the color of the text should be the gradient color (used in background of body).

**Comment by arpitghura** [comment] 2022-10-31 09:17
I am assigning this issue to you. You can now start your work.

> Okay @Shaba1406 It looks pretty good but needs some improvements like the copyright line should be placed at the bottom most part in center and the color of the text should be the gradient color (used in background of body).

**Comment by arpitghura** [comment] 2022-10-31 09:18
change the title to `updating footer`

**Comment by Shaba1406** [comment] 2022-10-31 09:41
can you please share your social media profile so i can link it with the social media icons.

**Comment by arpitghura** [comment] 2022-10-31 09:48
My Twitter, GitHub, LinkedIn all has the same username `arpitghura`. You can use this.

> can you please share your social media profile so i can link it with the social media icons.

**Comment by arpitghura** [comment] 2022-11-13 20:02
Hey @Shaba1406 are you currently working on this issue?

**Comment by Shaba1406** [comment] 2022-11-13 20:04
No i am not, you can assign it to someone else. Thankyou so much

**Comment by harsitagarwalla187** [comment] 2022-12-09 15:00
Can i work in this issue under KWOC?

**Comment by arpitghura** [comment] 2022-12-09 15:13
yeah @harsitagarwalla187 you can.

**Comment by SattyamSamania** [comment] 2022-12-25 16:38
@arpitghura Can I work on this if the issue is still open

**Comment by arpitghura** [comment] 2022-12-25 16:58
Yes, you can @SattyamSamania

**Comment by arpitghura** [comment] 2023-01-18 19:28
hey @SattyamSamania are you currently working on the issue? Do you need any help?

**Comment by Yash-Var** [comment] 2023-01-31 14:45
@arpitghura could you assign it to me..

**Comment by aviiciii** [comment] 2023-01-31 14:55
![image](https://user-images.githubusercontent.com/88141521/215794374-79f2ac67-02ea-442e-bac1-06ba322c83ac.png)
I have noticed that the footer has not been positioned to the bottom of the page but rather is fixed to the end of html. @arpitghura Shall I fix this bug under Diversion 2k22.

**Comment by arpitghura** [comment] 2023-02-01 05:32
Hey @aviiciii Welcome to the community, you can now start contributing to this issue. I am assigning it to you.

**Comment by aviiciii** [comment] 2023-02-01 06:56
Sure, I am looking forward to working on it.

**Comment by MiheerTamkhane** [comment] 2023-02-01 07:05
Hey, @arpitghura I saw the project and thought I can contribute to it,  can I work on this if the issue is still open?

**Comment by arpitghura** [comment] 2023-02-01 18:30
> Hey, @arpitghura I saw the project and thought I can contribute to it, can I work on this if the issue is still open?

Hey @MiheerTamkhane Thanks for showing interest. As @aviiciii is already working on this issue, you can look into some other issues.

**Comment by Shantanu-Meta** [comment] 2023-02-02 18:01
Hey @arpitghura , I have idea to link your discord, linkedIn, instagram and email as a contact us in footer. 
https://ibb.co/dkFBCFN here is the canges ?
Can I do that ?

**Comment by arpitghura** [comment] 2023-02-03 12:08
Hey @Shantanu-Meta the social media handles will not look professional. So, we cannot add them to the website. You can look into some other issues.

**Closed** 2023-02-03 12:08 UTC
Labels: enhancement, good first issue, diversion2k23

**Comment by Shantanu-Meta** [comment] 2023-02-03 17:37
> Hey @Shantanu-Meta the social media handles will not look professional. So, we cannot add them to the website. You can look into some other issues.

okay I got it. Actually I am a begainer contributor through DIVERSION 2K23. So could you please assign me some tasks releted with HTML & CSS ?
